apiVersion: v1
kind: Service
metadata:
  name: certauto-metrics
  namespace: certauto-system
  labels:
    app.kubernetes.io/name: certauto
    app.kubernetes.io/instance: certauto
    release: kube-prometheus-stack
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: certauto-metrics
  namespace: certauto-system
subsets:
  - addresses:
      - ip: 10.43.96.181
    ports:
      - name: metrics
        port: 8080
